# Generated by Django 2.0 on 2017-12-15 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pricegen.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Дата/время модификации')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(max_length=50, unique=True, validators=[pricegen.utils.ShortNameValidator()], verbose_name='Краткое (латинское) название')),
                ('role', models.CharField(choices=[('supplier', 'Поставщик'), ('retailer', 'Продавец')], max_length=50, verbose_name='Тип')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменивший')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='PickPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Дата/время модификации')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(max_length=50, unique=True, validators=[pricegen.utils.ShortNameValidator()], verbose_name='Краткое (латинское) название')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменивший')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Org', verbose_name='Организация')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pickpoint',
            unique_together={('org', 'name')},
        ),
    ]
