# Generated by Django 2.0 on 2017-12-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='role',
        ),
    ]
