# Generated by Django 2.0 on 2017-12-15 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Дата/время модификации')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменивший')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickPointBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Дата/время модификации')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricelists.Brand')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменивший')),
                ('pickpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PickPoint')),
            ],
        ),
        migrations.CreateModel(
            name='PickPointDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Дата/время модификации')),
                ('delivery_time', models.PositiveIntegerField(verbose_name='Время доставки (мин.)')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменивший')),
                ('pickpoint_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.PickPoint')),
                ('pickpoint_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.PickPoint')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pickpointdelivery',
            unique_together={('pickpoint_from', 'pickpoint_to')},
        ),
        migrations.AlterUniqueTogether(
            name='pickpointbrand',
            unique_together={('pickpoint', 'brand')},
        ),
    ]
