# Generated by Django 2.0 on 2017-12-20 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricelists', '0005_auto_20171218_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время создания')),
                ('dt_modified', models.DateTimeField(auto_now=True, verbose_name='Дата/время модификации')),
                ('inner_id', models.CharField(max_length=255)),
                ('partnumber', models.CharField(max_length=255)),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivery_time', models.PositiveIntegerField()),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменивший')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
