# Generated by Django 2.0 on 2017-12-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0006_exceltempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltempo',
            name='delivery_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exceltempo',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=15),
        ),
    ]
