# Generated by Django 2.0 on 2017-12-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0007_auto_20171221_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceltempo',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='exceltempo',
            name='dt_created',
        ),
        migrations.RemoveField(
            model_name='exceltempo',
            name='dt_modified',
        ),
        migrations.RemoveField(
            model_name='exceltempo',
            name='modifier',
        ),
    ]
