# Generated by Django 2.0 on 2017-12-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0009_auto_20171226_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceltempo',
            options={'ordering': ['row']},
        ),
        migrations.AlterIndexTogether(
            name='exceltempo',
            index_together={('brand', 'row')},
        ),
    ]
