# Generated by Django 2.0 on 2017-12-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0010_auto_20171226_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marge',
            options={'ordering': ('pickpoint', 'kind', 'limit')},
        ),
    ]
